# Generated by Django 6.0.3 on 2026-03-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('EBS', 'Elastic Block Store'), ('EIP', 'Elastic IP')], max_length=10)),
                ('monthly_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
