# Generated by Django 6.0.3 on 2026-03-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='resource_type',
            field=models.CharField(choices=[('EBS', 'Idle Volume'), ('EIP', 'Unused Elastic IP')], max_length=10),
        ),
    ]
