# Generated by Django 6.0.3 on 2026-04-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_wastereport_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='resource_type',
            field=models.CharField(choices=[('EBS', 'Idle Volume'), ('EIP', 'Unused Elastic IP'), ('RDS', 'Idle Database')], max_length=10),
        ),
    ]
