# Generated by Django 6.0.3 on 2026-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_wastereport_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='resource_type',
            field=models.CharField(choices=[('EBS', 'Idle Volume'), ('EIP', 'Unused Elastic IP'), ('RDS', 'Idle Database'), ('SNAP', 'Old DB Snapshot'), ('ELB', 'Idle Load Balancer'), ('NAT', 'Active NAT Gateway'), ('EC2', 'Stopped EC2(Storage)')], max_length=10),
        ),
    ]
